package dto;

import java.io.Serializable;

/**
 * 새 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class CommentDto implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** cId. */
	private Integer cId;

	/** cContents. */
	private String cContents;

	/** cRate. */
	private Integer cRate;

	/** 새 테이블. */
	private UserDto user;

	/** 새 테이블. */
	private RestaurantDto restaurant;
	
	public CommentDto(){
		
	}

	public Integer getcId() {
		return cId;
	}

	public void setcId(Integer cId) {
		this.cId = cId;
	}

	public String getcContents() {
		return cContents;
	}

	public void setcContents(String cContents) {
		this.cContents = cContents;
	}

	public Integer getcRate() {
		return cRate;
	}

	public void setcRate(Integer cRate) {
		this.cRate = cRate;
	}

	public UserDto getUser() {
		return user;
	}

	public void setUser(UserDto user) {
		this.user = user;
	}

	public RestaurantDto getRestaurant() {
		return restaurant;
	}

	public void setRestaurant(RestaurantDto restaurant) {
		this.restaurant = restaurant;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}


}
