package dto;

import java.io.Serializable;

/**
 * 새 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class MenuDto implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** mId. */
	private Integer mId;

	/** mName. */
	private String mName;

	/** mPrice. */
	private Integer mPrice;

	/** mPicture1. */
	private String mPicture1;

	/** mPicture2. */
	private String mPicture2;

	/** 새 테이블. */
	private RestaurantDto restaurant;

	/** mCategory. */
	private String mCategory;
	
	public MenuDto(){
		
	}
	

	public Integer getmId() {
		return mId;
	}

	public void setmId(Integer mId) {
		this.mId = mId;
	}

	public String getmName() {
		return mName;
	}

	public void setmName(String mName) {
		this.mName = mName;
	}

	public Integer getmPrice() {
		return mPrice;
	}

	public void setmPrice(Integer mPrice) {
		this.mPrice = mPrice;
	}

	public String getmPicture1() {
		return mPicture1;
	}

	public void setmPicture1(String mPicture1) {
		this.mPicture1 = mPicture1;
	}

	public String getmPicture2() {
		return mPicture2;
	}

	public void setmPicture2(String mPicture2) {
		this.mPicture2 = mPicture2;
	}

	public RestaurantDto getRestaurant() {
		return restaurant;
	}

	public void setRestaurant(RestaurantDto restaurant) {
		this.restaurant = restaurant;
	}

	public String getmCategory() {
		return mCategory;
	}

	public void setmCategory(String mCategory) {
		this.mCategory = mCategory;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	

}
