package dto;

import java.io.Serializable;

/**
 * 새 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Menu implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** mId. */
	private Integer mid;

	/** mName. */
	private String mname;

	/** mPrice. */
	private Integer mprice;

	/** mPicture1. */
	private String mpicture1;

	/** mPicture2. */
	private String mpicture2;

	/** 새 테이블. */
	private Restaurant restaurant;

	/**
	 * 생성자.
	 */
	public Menu() {
	}

	/**
	 * mId을 설정합니다..
	 * 
	 * @param mid
	 *            mId
	 */
	public void setMid(Integer mid) {
		this.mid = mid;
	}

	/**
	 * mId을 가져옵니다..
	 * 
	 * @return mId
	 */
	public Integer getMid() {
		return this.mid;
	}

	/**
	 * mName을 설정합니다..
	 * 
	 * @param mname
	 *            mName
	 */
	public void setMname(String mname) {
		this.mname = mname;
	}

	/**
	 * mName을 가져옵니다..
	 * 
	 * @return mName
	 */
	public String getMname() {
		return this.mname;
	}

	/**
	 * mPrice을 설정합니다..
	 * 
	 * @param mprice
	 *            mPrice
	 */
	public void setMprice(Integer mprice) {
		this.mprice = mprice;
	}

	/**
	 * mPrice을 가져옵니다..
	 * 
	 * @return mPrice
	 */
	public Integer getMprice() {
		return this.mprice;
	}

	/**
	 * mPicture1을 설정합니다..
	 * 
	 * @param mpicture1
	 *            mPicture1
	 */
	public void setMpicture1(String mpicture1) {
		this.mpicture1 = mpicture1;
	}

	/**
	 * mPicture1을 가져옵니다..
	 * 
	 * @return mPicture1
	 */
	public String getMpicture1() {
		return this.mpicture1;
	}

	/**
	 * mPicture2을 설정합니다..
	 * 
	 * @param mpicture2
	 *            mPicture2
	 */
	public void setMpicture2(String mpicture2) {
		this.mpicture2 = mpicture2;
	}

	/**
	 * mPicture2을 가져옵니다..
	 * 
	 * @return mPicture2
	 */
	public String getMpicture2() {
		return this.mpicture2;
	}

	/**
	 * 새 테이블을 설정합니다..
	 * 
	 * @param restaurant
	 *            새 테이블
	 */
	public void setRestaurant(Restaurant restaurant) {
		this.restaurant = restaurant;
	}

	/**
	 * 새 테이블을 가져옵니다..
	 * 
	 * @return 새 테이블
	 */
	public Restaurant getRestaurant() {
		return this.restaurant;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((mid == null) ? 0 : mid.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Menu other = (Menu) obj;
		if (mid == null) {
			if (other.mid != null) {
				return false;
			}
		} else if (!mid.equals(other.mid)) {
			return false;
		}
		return true;
	}

}
