package dto;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 새 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RestaurantDto implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** rId. */
	private Integer rId;

	/** rName. */
	private String rName;

	/** rAddress. */
	private String rAddress;

	/** rDistance. */
	private Integer rDistance;

	/** rOpenHours. */
	private String rOpenHours;

	/** rTel. */
	private String rTel;

	/** rRate. */
	private Integer rRate;

	private String rCategory;

	public Integer getrId() {
		return rId;
	}

	public void setrId(Integer rId) {
		this.rId = rId;
	}

	public String getrName() {
		return rName;
	}

	public void setrName(String rName) {
		this.rName = rName;
	}

	public String getrAddress() {
		return rAddress;
	}

	public void setrAddress(String rAddress) {
		this.rAddress = rAddress;
	}

	public Integer getrDistance() {
		return rDistance;
	}

	public void setrDistance(Integer rDistance) {
		this.rDistance = rDistance;
	}

	public String getrOpenHours() {
		return rOpenHours;
	}

	public void setrOpenHours(String rOpenHours) {
		this.rOpenHours = rOpenHours;
	}

	public String getrTel() {
		return rTel;
	}

	public void setrTel(String rTel) {
		this.rTel = rTel;
	}

	public Integer getrRate() {
		return rRate;
	}

	public void setrRate(Integer rRate) {
		this.rRate = rRate;
	}

	public String getrCategory() {
		return rCategory;
	}

	public void setrCategory(String rCategory) {
		this.rCategory = rCategory;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	

}
