package dto;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * 새 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UserDto implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** uId. */
	private Integer uId;

	/** uName. */
	private String uName;

	/** uEmail. */
	private String uEmail;

	/** uPassword. */
	private String uPassword;

	/** uGender. */
	private String uGender;

	/** uAge. */
	private Integer uAge;

	/** uPreference. */
	private String uPreference;

	public Integer getuId() {
		return uId;
	}

	public void setuId(Integer uId) {
		this.uId = uId;
	}

	public String getuName() {
		return uName;
	}

	public void setuName(String uName) {
		this.uName = uName;
	}

	public String getuEmail() {
		return uEmail;
	}

	public void setuEmail(String uEmail) {
		this.uEmail = uEmail;
	}

	public String getuPassword() {
		return uPassword;
	}

	public void setuPassword(String uPassword) {
		this.uPassword = uPassword;
	}

	public String getuGender() {
		return uGender;
	}

	public void setuGender(String uGender) {
		this.uGender = uGender;
	}

	public Integer getuAge() {
		return uAge;
	}

	public void setuAge(Integer uAge) {
		this.uAge = uAge;
	}

	public String getuPreference() {
		return uPreference;
	}

	public void setuPreference(String uPreference) {
		this.uPreference = uPreference;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	

}
